### ISSUE TITLE
Reqnroll or SpecFlow Plugin

### ISSUE THREAD

**Issue by mpcreza** [jfversluis/Template.Maui.UITesting#14]
How to use Reqnroll or SpecFlow in this template?

**Comment by jfversluis** [comment]
I'm not very familiar with either. It looks like these build on top of NUnit, xUnit and MSTest so it might be possible to work with all of this. I'd be happy to look at any PRs or something anyone might provide for this, but right now I don't have any immediate plans to add this.

Thanks!
