### ISSUE TITLE
Add  <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>  to the csproj file of the Shared project template

### ISSUE THREAD

**Issue by rhires** [jfversluis/Template.Maui.UITesting#9]
Using the templates, I have UITests.Shared, UITests.Android, and UITests.Windows. When I compile, though, I get a `CS0579: Duplicate 'AssemblyVersion' attribute` error for Android and Windows, because the Android and Windows test projects have the same assembly version. I discovered that if I remove the obj folder from the Shared project that I can get a clean build. If I try to rebuild, I get the error back, and I have to delete the obj folder from the Shared project in order to build. 

Turns out that in the Shared project I have to add  `<GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>`  to prevent that error from occurring, which also prevents the obj folder from being generated as well. I found my solution [here](https://stackoverflow.com/questions/61997928/errorcs0579duplicate-globalsystem-runtime-versioning-targetframeworkattribu/63853501#63853501) - though there are related answers [here](https://stackoverflow.com/questions/10311347/duplicate-assemblyversion-attribute) as well. You may wish to review the various answers because it seems that adding the templates the way I did caused me issues with running them, but others may have their own issues different from what I experienced. 

ETA: this was for the xunit project templates.

**Comment by jfversluis** [comment]
Interesting, thanks for reporting this, I will have a look! Just to be super clear on what you did... How did you add these to your solution? Visual Studio? CLI?

**Comment by rhires** [comment]
I added them via Visual Studio.
